name: Breast Cancer detection
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- pytorch
- numpy
- tqdm
- tensorboard
- protobuf<=3.20
- pip
- pip:
  - torchvision
  - onnx
  - wandb
  - onnxruntime
  - ipykernel
  - timm
